### PR TITLE
New native MIDI framework

### PR DESCRIPTION
**Pull request by louyihua**
In this framework, the native MIDI files does not hold the global player variable, and the only global variable needed is in `midi.c`. Current status:

- [x] Windows Desktop
- [x] Universial Windows Platform
- [x] Linux (verified under ubuntu yakkety)
- [x] Android
- [x] macOS
- [x] iOS

### CODE REVIEW

**Comment by palxex** [comment]
Matched interface for iOS/macOS.
Android seems not playing( keeps silent ) on my bacon 7.1.1. In `adb logcat` the midi already being readed in, but just not start play.

**Comment by louyihua** [comment]
Seems MIDI play does not work correctly on Android 6.0 or higher?

**Comment by palxex** [comment]
@louyihua not sure, I only have a 7.1.1 device. In my test, current master plays midi, this branch not, though from code it should work too. 
@PalMusicFan could you make a test?

**Comment by louyihua** [comment]
On my Android 6.0 emulator, neither version plays.
But under Android 4.4 emulator, the new model plays, too.

**Comment by palxex** [comment]
@PalMusicFan reported his Android 5.0 also not play in new model( plays in old model ). Waiting more test.

**Comment by PalMusicFan** [comment]
Test again with a Android 2.3 device. The new model doesn't play (plays in the old model).

**Comment by louyihua** [comment]
This version may have some bug. I'll push a new commit (that I tested yesterday) later today.

**Comment by louyihua** [comment]
New commit pushed.
 @PalMusicFan could you please do some test?

**Comment by palxex** [comment]
Verified works well on my device ( CM14.1 OPO )

**Comment by PalMusicFan** [comment]
It works well on both devices (Android 2.3.6 and 5.0).

**Comment by louyihua** [comment]
@PalMusicFan If you have time, please do the test. I can only verify UWP on PC.

**Comment by PalMusicFan** [comment]
It works well on my WP device!

**Comment by palxex** [comment]
Great, found the UWP new modal fixed the MIDI random reset problem.

**Comment by louyihua** [comment]
@PalMusicFan 
I'll check the UWP Win32 version later today.
But I think there should be no needs to keep Windows 8.1 version maintained.

**Comment by PalMusicFan** [comment]
Since there is no formal Windows 10 Mobile Release for Nokia devices like Lumia 525  (I am using a device running Insider version of Win10 Mobile), I think it is better to keep Windows Phone 8.1 version for a longer period if it is possible and not too difficult. :-)

**Comment by PalMusicFan** [comment]
It seems something is wrong with win32 desktop version. 
If I build it with MSYS2, MIDI music plays much too fast. 
In MinGW Distro: 

native_midi.cpp: In function 'void native_midi_stop(NativeMidiSong*)':
native_midi.cpp:324:9: error: 'NativeMidiSong {aka struct _NativeMidiSong}' has no member named 'Stop'
   song->Stop.notify_all();
         ^~~~
native_midi.cpp:325:13: error: 'NativeMidiSong {aka struct _NativeMidiSong}' has no member named 'Thread'
   if (song->Thread.joinable())
             ^~~~~~
native_midi.cpp:326:10: error: 'NativeMidiSong {aka struct _NativeMidiSong}' has no member named 'Thread'
    song->Thread.join();
          ^~~~~~
native_midi.cpp:327:9: error: 'NativeMidiSong {aka struct _NativeMidiSong}' has no member named 'Thread'
   song->Thread = std::move(std::thread());
         ^~~~~~
native_midi.cpp:327:28: error: 'thread' is not a member of 'std'
   song->Thread = std::move(std::thread());
                            ^~~
make: *** [Makefile.mingw:42: native_midi.o] Error 1

**Comment by louyihua** [comment]
@PalMusicFan The UWP x86 build is fixed on master.
But for the Win 8.1, since I no longer have a development environment, so it may be difficult to add new platform-dependent features. And further, VS2013 does not have the full concurrency support until a special feature pack is installed, so it makes things even harder. So currently the best solution is to disable native MIDI (as well as future platform-dependent features) for non-UWP WinRT versions.

**Comment by louyihua** [comment]
@PalMusicFan
What version of MinGW distro do you use?
Your compilation error seems to be a GCC version that does not support `std::thread`

**Comment by PalMusicFan** [comment]
You can get it (version 14.1 with GCC 6.3.0) here: https://nuwen.net/mingw.html
It is really a portable solution.

**Comment by louyihua** [comment]
@PalMusicFan 
The speed problem is solved (my fault of misuse the std::chrono::system_clock::duration).
The makefile is updated, could you try to compile it in MinGW distro again?

**Comment by PalMusicFan** [comment]
Playing speed problem solved. 
There occurs even more errors when compiling with MinGW Distro.

**Comment by louyihua** [comment]
@PalMusicFan
The MinGW problem is caused by incomplete implementation of some MinGW distributions (includes MinGW distro). It is completely solved through importing a third-party library 'mingw-std-threads'. You can test for yourself.

**Comment by louyihua** [comment]
As long as the MinGW problem is verified by @PalMusicFan , this PR can be considered complete and can be merged.

**Comment by palxex** [comment]
Verified works well under both MSYS2 and nuwen's MinGW Distro. The new model seems also fixed the MIDI looping crash that occurs frequently in MSYS2 compiled binaries, which I previous thought caused by windows 10 fast ring update.

**Comment by louyihua** [comment]
Merge it.

**Comment by PalMusicFan** [comment]
@louyihua Nuwen's MinGW Distro now complies well. 
Would you please fix Windows 8.1 / Windows Phone 8.1 projects?

**Comment by louyihua** [comment]
@PalMusicFan
I've made the Win 8.1 projects pass compilation through the help from appveyor. But I can't gurantee the generated binary works since I don't have any debugging environment locally.

**Comment by PalMusicFan** [comment]
@louyihua Tested! It works well on both Lumia 525 and Windows 10.
